version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: project_upx_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=upx
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '3001:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -q -d upx -U user']
      interval: 5s
      timeout: 2s
      retries: 20
